services:
  ngrok:
    image: ngrok/ngrok:latest
    env_file: .env
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: start authentik --config /etc/ngrok/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml
    restart: "no"
    networks:
      - sso-net

networks:
  sso-net:
    external: true
    name: sso-net